name: Android CI

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle
        run: date -u

  second-job:
    runs-on: windows-latest
    steps:
      - name: print date on windows
        run: date /t

  thired-job:
      runs-on: macOS-latest
      steps:
        - name: print date on macOS
          run: date -u

  fourth-job:
    runs-on: ubuntu-latest
    needs: [first-job, second-job, thired-job]
    steps:
      - name: print date on ubuntu for 2nd time
        run: date -u
